---
baseurl: "http://twin-peaks.com/"
languageCode: "en-us"
title: "Twin Peaks"
paginate: 5
copyright: "All rights reserved - 2016"
canonifyurls: true
disqusShortname: "YOUR_SHORT_NAME_HERE"

params:
  description: "Who killed Laura Palmer?"
  cover: "/images/cover.jpg"
  author: "Agent Cooper" 
  logo: "/images/logo.png"
  googleAnalyticsUserID: "YOUR_GA_ID_HERE"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink: "http://feeds.feedburner.com/..." 
  githubName: "dencold"
  twitterName: "dencold"
  hideHUGOSupport: true
  shares: 
    twitter: false
    facebook: true
    google-plus: true

author:
  dennis:
    name: "Agent Cooper"
    location: "Washington, D.C."
    bio: "in search of damned good coffee"
    thumbnail: "/images/avatar.jpg"

menu:
  main:
    - name: "Blog"
      weight: -120
      identifier: "blog"
      url: "/"
    - name: "About"
      weight: -110
      identifier: "about"
      url: "/about"
  
